Add endpoint for saving token data
kleros/kleros-microservices pull request #4
Opened 2018-10-31 12:50 UTC by mtsalenc

2018-11-01 14:34 UTC, epiqueras commented on serverless.yml
> +      summary: 'Upload token data.'
Upload => Update

2018-11-01 14:35 UTC, epiqueras commented on serverless.yml
> +      description: 'Takes token data and stores it by content-address.'
"Update token data for a content address (what is a content address?)."

2018-11-01 14:40 UTC, epiqueras commented on src/tokens-on-trial/models/token.json
> +              "description": "The token ticker symbol."
The token's ticker.

2018-11-01 14:41 UTC, epiqueras commented on src/tokens-on-trial/models/token.json
> +            "uri": {
URI

2018-11-01 14:42 UTC, epiqueras commented on src/tokens-on-trial/models/token.json
> +              "description": "The uploaded token data."
Missing properties.

2018-11-01 14:45 UTC, epiqueras commented on src/tokens-on-trial/token.js
> +module.exports.patch = async (event, _context, callback) => {
What you are doing is a PUT not a PATCH.

2018-11-01 14:45 UTC, epiqueras commented on src/tokens-on-trial/token.js
> +          UpdateExpression: keys.map(k => `SET ${k} = :_${k}`).join(', '),
These are all part of Update/Patch Item. This won't work, see AWS docs.

2018-11-01 14:45 UTC, epiqueras commented on yarn.lock
>    dependencies:
Make sure you have the latest version of yarn.

2018-11-01 14:45 UTC, epiqueras requested changes
Good start.

2018-11-01 17:23 UTC, eccentricexit commented on serverless.yml
> +      description: 'Takes token data and stores it by content-address.'
~This is to mean that the key used to fetch token data will be the hash of that data.~
Nevermind, I misunderstood how dynamoDB queries would work.

2018-11-06 14:58 UTC, mtsalenc commented
We can use cfs for storing token data, which means this is no longer required.

2018-11-06 14:58 UTC, closed without merging